### ISSUE TITLE
Is there any function to delete an workgroup?

### ISSUE THREAD

**Issue by OsicKwon** [pashinin/workgroups2#100]
Thank you for this wonderful package for session management.

I can only see save and open workgroup functions like below.
How can I delete an workgroup that I don't need any more?

![image](https://user-images.githubusercontent.com/5477324/116468311-b13dfb00-a83e-11eb-8e49-bcf8e23ad090.png)

**Comment by redguardtoo** [comment]
not yet. you can override workgroup with same name. Or open ~/.emacs_workgroups and delete the group.

**Comment by OsicKwon** [comment]
Thank you for your quick response. I also think that's the best way for now to kill the workgroup that is not used any more.

**Comment by luluman** [comment]
> Thank you for your quick response. I also think that's the best way for now to kill the workgroup that is not used any more.

Yes. I totally agree. The most used commands of "workgroups" in my daily workflow are "create," "delete," "rename," "switch" I never use save session and restore because I work in the remote terminal and attach to emacs daemon using emacsclient. "Workgroups" is gratifying to fulfill all my needs, and I hope those features I mention above could be preserved when this project evolves. 

Also, there are some drawbacks in "workgroups": when I use LSP(eglot), there are many temp buffers in the background. "workgroups" try to manage those buffer and brings lots of performance penalty. I think it is OK to keep an eye on the change of visual frame and ignore all the background buffers when users do not need to save sessions.

I am very grateful to @redguardtoo for his refactoring work.

**Comment by redguardtoo** [comment]
f9479da can delete work group (Chen Bin)
