### ISSUE TITLE
Profiler on Emacs, found workgroups2 is really heave. Why?

### ISSUE THREAD

**Issue by stardiviner** [pashinin/workgroups2#68]
![2015-08-27-155717_1366x768_scrot](https://cloud.githubusercontent.com/assets/378699/9515722/c8b3ad2c-4cd5-11e5-9c95-d50643c47788.png)

**Comment by boykov** [comment]
I also noticed that switching workgroups latency degrades in the course of time. First hours (or days) after restart switching is fast but then delay grows.

**Comment by panaak** [comment]
I seem to have the same problem. Does anyone have an explanation? Is it maybe because I have quite a number of defined workgroups (about 20) ? I'm not realy that experienced enough with elisp to debug and understand the profile report.. :/

**Comment by rokadias** [comment]
Yeah, I'm having the same issue. Workgroups2 starts slowing down the more buffers I have open and the longer I'm using it.

Otherwise Workgroups2 is by far the best workspace manager out there for me, and has all the features I was looking for.

**Comment by boykov** [comment]
I noticed that big savehist-file slows down workgroups2. I've just removed 1Mb history file and workgroups2 is fast now.

**Comment by rokadias** [comment]
Not really aware of a savehist file. I did however notice in my profiling that the equal-bufobjs seemed to be the performance bottleneck.

https://github.com/pashinin/workgroups2/blob/master/src/workgroups2.el#L3098

There's a comment suggesting it needs to be smarter, and I'll probably assume faster as well.

Since this gets less peformant as I get more buffers. I decided to add a limit to the number of buffers it will work with.

Basically added the if statement line within `wg-add-buffer-to-buf-list`:
```elisp
(push buf (wg-buf-list))
(if (> (length (wg-buf-list)) 100) (nbutlast (wg-buf-list)))
```
https://github.com/pashinin/workgroups2/blob/master/src/workgroups2.el#L3176

If the length of the list is greater than 100 then remove the last item in the list. Which adds somewhat of a limiting factor on the length of the list. After making this change. My emacs runs faster overall and it hasn't slow down over time.

**Comment by panaak** [comment]
@rokadias tried to implement your solution, but after reaching the limit, defined workgroups end up with the same (last) buffer in every window.

**Comment by FrancisMurillo** [comment]
@panaak Wouldn't the specified hack or fix not find the correct buffer if its popped off the list?

**Comment by panaak** [comment]
Just realized, that my `wg-buf-list` looks like this:

```
(length (wg-buf-list))
4249

(list (wg-buf-list))
(([cl-struct-wg-buf "0HKE0MPMHSN3F5IW-5CCZZ2" " *temp*-231223" nil 5 nil (... nil nil nil nil nil nil nil) nil nil] [cl-struct-wg-buf "0HKE0MPMH9U5B1DK-5CCZNR" " *temp*-90836" nil 6 nil (... nil nil nil nil nil nil nil) nil nil] [cl-struct-wg-buf "0HKE0MPMH0DW6WGG-5CCZCL" " *temp*-935731" nil 4 nil (... nil nil nil nil nil nil nil) nil nil] [cl-struct-wg-buf "0HKE0MPMGQJ1GZVS-5CCZ14" " *temp*-814026" nil 8 nil (... nil nil nil nil nil nil nil) nil nil] [cl-struct-wg-buf "0HKE0MPMGGQXA474-5CCYPJ" " *temp*-108941" nil 7 nil (... nil nil nil nil nil nil nil) nil nil] [cl-struct-wg-buf "0HKE0MPMG739HXU0-5CCYDM" " *temp*-613686" nil 9 nil (... nil nil nil nil nil nil nil) nil nil] [cl-struct-wg-buf "0HKE0MPMFXKK1Y7S-5CCY0J" " *temp*-673005" nil 18 nil (... nil nil nil nil nil nil nil) nil nil] [cl-struct-wg-buf "0HKE0MPMFNPREYKW-5CCXNM" " *temp*-831450" nil 14 nil (... nil nil nil nil nil nil nil) nil nil] [cl-struct-wg-buf "0HKE0MPMFDSMGF1S-5CCXAX" " *temp*-591382" nil 14 nil (... nil nil nil nil nil nil nil) nil nil] [cl-struct-wg-buf "0HKE0MPMF3R81Y7S-5CCWY8" " *temp*-962289" nil 14 nil (... nil nil nil nil nil nil nil) nil nil] [cl-struct-wg-buf "0HKE0MPMEU539LOG-5CCWLZ" " *temp*-247158" nil 10 nil (... nil nil nil nil nil nil nil) nil nil] [cl-struct-wg-buf "0HKE0MPMEH8M8KN4-5CCWA4" " *temp*-441241" nil 6 nil (... nil nil nil nil nil nil nil) nil nil] ...))

```
most of the buffers are "*temp*-\d+", not really sure what is creating those..

**Comment by panaak** [comment]
```
(defun wg-add-buffer-to-buf-list (buffer)
  "Make a buf from BUFFER, and add it to `wg-buf-list' if necessary.
If there isn't already a buf corresponding to BUFFER in
`wg-buf-list', make one and add it.  Return BUFFER's uid
in either case."
  (when buffer
  (with-current-buffer buffer
    (setq wg-buffer-uid
          (aif (wg-find-buffer-in-buf-list buffer (wg-buf-list))
              (wg-buf-uid it)
            (let ((buf (wg-buffer-to-buf buffer)))
			  (unless (string-match "^\s*\\*temp\\*-[0-9]+$" (wg-bufobj-name buf))
				(push buf (wg-buf-list)))
			  (wg-buf-uid buf)))))))
```
this ugly hack seems to fix the issue. i've been using this for quite some time without any apparent side effects. it would be better to use some kind of blacklist function similar to const `wg-autoassociate-blacklist` or i might be wrong. don't really have the time to mess with this right now.

**Comment by m-cat** [comment]
Hello, fellow Emacseners. I have come to make a humble inquiry as to whether this issue is still extant, four years hence. Indeed, the project by and large looks quite promising and it does tickle my fancy to try it, but alack, I tend to keep many buffers open for long periods of time, and am loathe of inexplicable slowdowns, lags, latencies, hiccups, and dawdles. As a master-level software developer, I have not the hours to wait for my software to catch up with my thought process, and I therefore am not able to tolerate idle dilly-dallying whilst I am in the midst of fruitful endeavor. My hope is that the kind people here understand my plight, and that my humble message causes no offense, for I am sure that the issue has been quite a vexing one for it to remain unresolved these many moons later (for it can easily be said that four years in the software world is the equivalent of half a lifetime), or perhaps the authors, who I'm sure must be master-level software developers themselves, simply have had not the wherewithal to approach this matter and ascertain the cause as it is merely one of 35 issues written on this repository, all of which I'm sure must be of high import and hefty matters of high significance in themselves.

**Comment by redguardtoo** [comment]
@m-cat , this performance issue should be resolved. I removed the hook. Currently I'm the maintainer of this project.

My philosophy is wg2 should focus on saving/loading windows layout only. Nothing else. It should be fast and support all types of windows.

I've not reviewed the old issues yet. You could highlight any old issue I should look into.
