### ISSUE TITLE
eventually causes emacs to hang hard at startup, hard to recover workgroups

### ISSUE THREAD

**Issue by simonmichael** [pashinin/workgroups2#70]
Thanks for maintaining workgroups. I've been using workgroups2 20140831.1107 for a while. Today I found that emacs hangs at startup, unless I remove the workgroups session file. This has happened before. That file contains a lot of accumulated workgroups setup, and unfortunately being one huge line it's rather difficult to edit and recover.

**Comment by simonmichael** [comment]
In this particular case I eventually was able to reload the session mostly intact - perhaps due to upgrading to workgroups2 20141102.1122.

**Comment by pashinin** [comment]
I started to hack Emacs code to rewrite workgroups because I don't know how to make this extension work properly in Elisp (it needs to be lower level). It hangs, slows things down, and full of hacks. But I want this functionality so I will try to do it in C.

Please use older versions if something isn't working for you now.

**Comment by redguardtoo** [comment]
Latest version does not have this issue. Feel free to re-open this ticket.

**Comment by simonmichael** [comment]
Very happy to see continued work on workgroups2, thanks! Looking forward to changelog/release when it's time.

**Comment by tomdavey** [comment]
Agreed! Workgroups2 is indispensable. Many thanks.

 

--

Tom Davey

 ***@***.***> ***@***.***

New York NY USA
