### ISSUE TITLE
add a yes-or-no confirm when switching workgroups with typo

### ISSUE THREAD

**Issue by stardiviner** [pashinin/workgroups2#72]
Sometimes, I switch to a workgroups, but has a typo, then workgroups auto created this session for me without a confirm. I have to delete it manually. So I hope to add a confirm.
Thanks for this useful utility.

**Comment by CNBorn** [comment]
I'd like to have a yes-or-no confirmation as well, but for `kill workgroup`. In my opinion even if you created a mis-spelled workgroup that's no big deal, you can use `wg-rename-workgroup` (wg-prefix then capital `A`) to rename it anytime you want. But killing a workgroup accidentally has consequences: you will lost the window-config for that workgroup.

**Comment by CNBorn** [comment]
Just notice that @stardiviner was mentioning `switch to a workgroup with typos lead to workgroup creation` rather than just `create workgroup with typo`. Although I was never accidentally triggering that (Thanks to ido),  I test it out and do find it annoying. Would be better to have a option for either yes-or-no confirmation when switching to non-existing workgroup or just disable workgroup creation from switching.

**Comment by redguardtoo** [comment]
Latest version does not have this issue. Feel free to re-open this ticket.
