### ISSUE TITLE
Add  buffer names as work-group name instead of wgN

### ISSUE THREAD

**Issue by Pitometsu** [pashinin/workgroups2#85]
First of all, thank you for great plugin! It's minor feature request.

- Would it be reasonable to name new workgroup by buffers there by default? Probably with counted prefix to avoid clashes. When I create workgroup usually I don't want to spend attention on naming. And until I name it, it would be good to see, what I have there for easy buffer switching or naming (easily understand purpose).
- Additionally, it would be great, if those unnamed workgroups would change names according to changes in buffer names/windows configuration.
- Also it can be useful, if renaming workgroup to `nil` or `""` would change name to default value with appropriate dynamic behaviour.

**Comment by Pitometsu** [comment]
About naming: I guess, it's possible even to encode current configuration like:
`0: - *scratch* | *Messages* *Help*`
or in Forth-style:
`0: *scratch* | *Messages* *Help* -`
(T-like splitting here).

**Comment by pashinin** [comment]
Please fork it and do changes you like

**Comment by Pitometsu** [comment]
@pashinin is such option would conflict with this project purposes?

Similar functianality already [implemented](http://grapevine.net.au/~striggs/elisp/workspaces.el) (a little clumsily) as `escreen` wrapper.

**Comment by pashinin** [comment]
No) I just don't work at this project. https://github.com/pashinin/workgroups2/issues/73

**Comment by Pitometsu** [comment]
Hope, this idea would be helpful if you keep trying [do it in C](https://www.youtube.com/watch?v=1S1fISh-pag) yet

**Comment by redguardtoo** [comment]
group name is provided by user now. so this feature will not be implemented.

**Comment by Pitometsu-GeniusYield** [comment]
@redguardtoo what I suggested is to improve UX: it's inconvenient to be distracted to the group naming exactly in the moment when you have an action in mind and what you want as a user is to jump into a fresh work-group to do it.  So that would be pretty convenient to have some default naming mechanism, which would help you avoid that distraction, and still be descriptive enough to be able to grasp what happening on each work-group by the name (e.g. buffer names, or/and projectile name).
